### PR TITLE
resolves #125 (use project ID from application credentials file)

### LINKED ISSUE #125: [EventPublisher] allow to override GCP Project ID
When I ran the wercker tests, the gcp tests failed due to hardcoded project ID.

### Problem description

The tests in `publisher/gcp/publisher_test.go` all use `"looplab-eventhorizon"` as project ID. 

Across GCP, project IDs are unique: when I created google pub/sub, mine was set to `looplab-eventhorizon-175016`. This caused the tests to fail.

### Suggested fix

The project ID is likely to be constant across all gcp EventPublisher tests. In addition, the `GOOGLE_APPLICATION_CREDENTIALS` JSON file (which is [required to authenticate](https://developers.google.com/identity/protocols/application-default-credentials) the tests) contains the `project_id`. This JSON value must also match the `projectID` used by `NewEventPublisher`

Hence my suggestion is a helper function that grabs the `project_id` from the `$GOOGLE_APPLICATION_CREDENTIALS` file, falling back to the current value as a constant.

### PR DESCRIPTION
**Pull request by grrtrr**
This extracts the `project_id` from the existing `GOOGLE_APPLICATION_CREDENTIALS` file, throwing an error if the file does not exist or is malformed (in this case the test would fail anyway).

### CODE REVIEW

File: publisher/gcp/publisher_test.go [hunk 1]
```diff
@@ -62,3 +65,26 @@ func TestEventBusAsync(t *testing.T) {
 
 	testutil.EventPublisherCommonTests(t, publisher1, publisher2)
 }
+
+// setUpEventPublisher is a helper that creates a new GCP publisher for @appID
+func setUpEventPublisher(appID string) (*EventPublisher, error) {
+	var projectID = "looplab-eventhorizon"
```
Comment (maxekman) [inline publisher/gcp/publisher_test.go]: Please use the `projectID := ""` form.

File: publisher/gcp/publisher_test.go [hunk 2]
```diff
@@ -62,3 +65,26 @@ func TestEventBusAsync(t *testing.T) {
...
+
+	// See https://developers.google.com/identity/protocols/application-default-credentials
+	if creds := os.Getenv("GOOGLE_APPLICATION_CREDENTIALS"); creds != "" {
+		var m = make(map[string]string)
```
Comment (maxekman) [inline publisher/gcp/publisher_test.go]: Use the := form and allocate with {} instead of `make`. Also move to the row above where it's first used.

File: publisher/gcp/publisher_test.go [hunk 3]
```diff
@@ -62,3 +65,26 @@ func TestEventBusAsync(t *testing.T) {
...
+
+		r, err := os.Open(creds)
+		if err != nil {
+			return nil, fmt.Errorf("unable to read credentials file: %s", err)
+		}
+		defer r.Close()
+
+		if err = json.NewDecoder(r).Decode(&m); err != nil {
```
Comment (maxekman) [inline publisher/gcp/publisher_test.go]: Use := in ifs with assignments.
